import java.io.IOException;


import VetClinic.VetClinic;

public class Client {

	public static void main(String[] args) throws IOException {
		// TODO Auto-generated method stub
		
	
	new VetClinic();
	
	// WELCOME TO MY CODE: MAIRA LORENA WALTERO GUEVARA 2019208
	
	// MY CLINIC IS DIVIDED IN TWO SUPER CLASES: 
	// 1. STAFF     AND   2. ANIMALS 
	
	// 1. STAFF HAS 3 CHILDS: 
	// 1.1  ADMINISTRATIVE STAFF     AND   1.2 MEDICAL STAFF
	// 1.1  ADMININSTRATIVE STAFF HAS 3 CHILDS: 
	//1.1.1 HR (id=229 -230)  ,   1.1.2   IT (id=226-228)   AND   1.1.3 RECEPTIONIST (id=221-225)
	
	// 1.2.  MEDICAL STAFF HAS 3 CHILDREN: 
	//1.2.1  SMALL ANIMALS VETS (id= 111 - 125)   ,   1.2.2  LARGE ANIMALS VETS  (id= 126 - 130)   AND    LABORATORIANS (id= 131 - 140) 
	//1.2.1  SMALL ANIMALS VETS is only attending small animals = pets 
	//1.2.2  LARGE ANIMALS VETS is only attending large animals = livestock animals 
	//1.2.3  LABORATORIANS are attending both type of animals but only if they need. 
	
	//2. ANIMALS HAS TWO SUBCLASSES: 
	//2.1  COMPANION ANIMALS     AND    2.2 LIVESTOCK ANIMALS 
	//2.1 COMPANION ANIMALS HAS 3 SUBCLASSES:
	//2.1.2  CAT    ,     2.1.2   DOG      AND       2.1.3 RABBIT 
	//2.2 LIVESTOCK ANIMALS HAS TWO SUBCLASSES: 
	//2.2.1  CATTLE        AND       2.2.2  SHEEP 
	
	// THE ARE TREE TYPES OF CLASES WHO CONTAIN THE METHODS IN ORDER TO CREATE THE FUNTIONS 
	// 1. READING FILES         , 2. MAIN CLASS OF METHODS        AND         3. PRINT AND QUESTION METHODS
	
	// 1. READING FILES: 
	// 1.1 INFOANIMALS AND INFOSTAFF : IN HERE THE METHOD READ THE FILE AND IN SOME CASES CREATE AN ARRAY LIST WITH RANDOM ELEMENTS 
	// 1.2 MAIN CLASS OF METHOS: IN HERE THERE ARE THE METHODS TO CREATE THE INTANCES, POPULATE THE QUEUES, ASSING TASKS AND DO THE SEARCHS 
	// 1.3 PRINT AND QUESTION METHODS: THIS CONTAIN THE METHODS TO ASK TO THE USER QUESTIONS AND PRINT THE ANSWER USING THE METHODS INSIDE OF INFORMATION CLASS
	}
	

}
